#ifndef PANDA_DEBURRING__FT_CALIBRAION_FILTER_
#define PANDA_DEBURRING__FT_CALIBRAION_FILTER_

// system
#include <Eigen/Dense>
#include <limits>
#include <memory>
#include <pinocchio/algorithm/frames.hpp>
#include <pinocchio/spatial/fwd.hpp>
#include <string>
#include <vector>

#include "controller_interface/controller_interface.hpp"
#include "geometry_msgs/msg/wrench_stamped.hpp"
#include "panda_deburring/butterworth_filter.hpp"
#include "realtime_tools/realtime_publisher.hpp"

// auto-generated by generate_parameter_library
#include "panda_deburring/ft_calibration_filer_parameters.hpp"

typedef Eigen::Matrix<double, 6, 1> Vector6d;
typedef Eigen::Matrix<double, 6, 3> Matrix63d;
typedef Eigen::Matrix<double, 6, -1> Matrix6Xd;

namespace panda_deburring {
class FTCalibrationFilter : public controller_interface::ControllerInterface {
 public:
  controller_interface::CallbackReturn on_init() override;

  controller_interface::InterfaceConfiguration command_interface_configuration()
      const override;

  controller_interface::InterfaceConfiguration state_interface_configuration()
      const override;

  controller_interface::CallbackReturn on_configure(
      const rclcpp_lifecycle::State &previous_state) override;

  controller_interface::CallbackReturn on_activate(
      const rclcpp_lifecycle::State &previous_state) override;

  controller_interface::CallbackReturn on_deactivate(
      const rclcpp_lifecycle::State &previous_state) override;

  controller_interface::return_type update(
      const rclcpp::Time &time, const rclcpp::Duration &period) override;

 protected:
  std::shared_ptr<ft_calibration_filter::ParamListener> param_listener_;
  ft_calibration_filter::Params params_;

  pinocchio::Model robot_model_;
  pinocchio::Data robot_data_;
  pinocchio::FrameIndex frame_of_interest_id_;

  bool bias_computed_ = false;
  std::size_t bias_buffer_cnt_ = 0;
  Matrix6Xd bias_measurements_;
  pinocchio::Force avg_bias_;
  pinocchio::Force force_;
  Eigen::VectorXd q_;
  Eigen::Vector3d g_;
  pinocchio::SE3 calibration_;
  Matrix63d calibration_trans_;

  std::vector<ButterworthFilter> filters_;

  std::vector<std::reference_wrapper<hardware_interface::LoanedStateInterface>>
      ordered_state_force_interfaces_;

  std::vector<std::reference_wrapper<hardware_interface::LoanedStateInterface>>
      ordered_state_robot_position_interfaces_;

  std::vector<
      std::reference_wrapper<hardware_interface::LoanedCommandInterface>>
      ordered_command_interfaces_;

  using StatePublisher =
      realtime_tools::RealtimePublisher<geometry_msgs::msg::WrenchStamped>;
  rclcpp::Publisher<geometry_msgs::msg::WrenchStamped>::SharedPtr
      sensor_state_publisher_;
  std::unique_ptr<StatePublisher> realtime_publisher_;
};
}  // namespace panda_deburring

#endif  // PANDA_DEBURRING__FT_CALIBRAION_FILTER_
