running_model:
  class: IAMSoftContactAugmented
  differential:
    class: DAMSoftContactAugmentedFwdDynamics
    Kp: [1000, 1000, 1000]
    Kv: [100, 100, 100]
    frame_id: ati_mini45_measurement_reference
    oPc: [0.0, 0.0, -0.073915]
    with_gravity_torque_reg: True
    enabled_directions: [True, True, True]
    ref: LOCAL_WORLD_ALIGNED
    cost_ref: LOCAL_WORLD_ALIGNED
    costs:
      - name: state_reg
        update: true
        weight: 1.0
        cost:
          class: CostModelResidual
          activation:
            class: ActivationModelWeightedQuad
            weights: 1.0
          residual:
            class: ResidualModelState
      - name: frame_rot_tracking_tool
        update: true
        weight: 1.0
        cost:
          class: CostModelResidual
          activation:
            class: ActivationModelWeightedQuad
            weights: 1.0
          residual:
            class: ResidualModelFrameRotationStatic
            frame_id: fer_ati_mini45_with_camera_tool
      - name: frame_pose_tracking_tool
        update: true
        weight: 1.0
        cost:
          class: CostModelResidual
          activation:
            class: ActivationModelWeightedQuad
            weights: 1.0
          residual:
            class: ResidualModelFrameTranslationStatic
            frame_id: fer_ati_mini45_with_camera_tool
            # - name: frame_velocity_tracking_tool
            #   update: true
            #   weight: 1.0
            #   cost:
            #     class: CostModelResidual
            #     activation:
            #       class: ActivationModelWeightedQuad
            #       weights: 1.0
            #     residual:
            #       class: ResidualModelFrameVelocityStatic
            #       reference_frame: LOCAL
            #       frame_id: fer_ati_mini45_with_camera_tool
            # - name: frame_velocity_tracking_sensor
            #   update: true
            #   weight: 1.0
            #   cost:
            #     class: CostModelResidual
            #     activation:
            #       class: ActivationModelWeightedQuad
            #       weights: 1.0
            #     residual:
            #       class: ResidualModelFrameVelocityStatic
            #       reference_frame: LOCAL
            #       frame_id: ati_mini45_measurement_reference
terminal_model:
  class: IAMSoftContactAugmented
  differential:
    class: DAMSoftContactAugmentedFwdDynamics
    Kp: [1000, 1000, 1000]
    Kv: [100, 100, 100]
    frame_id: ati_mini45_measurement_reference
    oPc: [0.0, 0.0, -0.073915]
    with_gravity_torque_reg: False
    enabled_directions: [True, True, True]
    ref: LOCAL_WORLD_ALIGNED
    cost_ref: LOCAL_WORLD_ALIGNED
    costs:
      - name: state_reg
        update: true
        weight: 1.0
        cost:
          class: CostModelResidual
          activation:
            class: ActivationModelWeightedQuad
            weights: 1.0
          residual:
            class: ResidualModelState
      - name: frame_rot_tracking_tool
        update: true
        weight: 1.0
        cost:
          class: CostModelResidual
          activation:
            class: ActivationModelWeightedQuad
            weights: 1.0
          residual:
            class: ResidualModelFrameRotationStatic
            frame_id: fer_ati_mini45_with_camera_tool
      - name: frame_pose_tracking_tool
        update: true
        weight: 1.0
        cost:
          class: CostModelResidual
          activation:
            class: ActivationModelWeightedQuad
            weights: 1.0
          residual:
            class: ResidualModelFrameTranslationStatic
            frame_id: fer_ati_mini45_with_camera_tool
            # - name: frame_velocity_tracking_tool
            #   update: true
            #   weight: 1.0
            #   cost:
            #     class: CostModelResidual
            #     activation:
            #       class: ActivationModelWeightedQuad
            #       weights: 1.0
            #     residual:
            #       class: ResidualModelFrameVelocityStatic
            #       reference_frame: LOCAL
            #       frame_id: fer_ati_mini45_with_camera_tool
# - name: frame_velocity_tracking_sensor
#   update: true
#   weight: 1.0
#   cost:
#     class: CostModelResidual
#     activation:
#       class: ActivationModelWeightedQuad
#       weights: 1.0
#     residual:
#       class: ResidualModelFrameVelocityStatic
#       reference_frame: LOCAL
#       frame_id: ati_mini45_measurement_reference
