agimus_pytroller:
  ros__parameters:
    type: agimus_pytroller/AgimusPytroller
    python_module: panda_deburring.deburring_controller
    python_downsample_factor: 2
    state_interfaces:
      - fer_joint1/position
      - fer_joint2/position
      - fer_joint3/position
      - fer_joint4/position
      - fer_joint5/position
      - fer_joint6/position
      - fer_joint7/position
      - fer_joint1/velocity
      - fer_joint2/velocity
      - fer_joint3/velocity
      - fer_joint4/velocity
      - fer_joint5/velocity
      - fer_joint6/velocity
      - fer_joint7/velocity
    command_interfaces:
      - fer_joint1/effort
      - fer_joint2/effort
      - fer_joint3/effort
      - fer_joint4/effort
      - fer_joint5/effort
      - fer_joint6/effort
      - fer_joint7/effort
    subscribed_topics: ["mpc_input"]
    mpc_input:
      topic_name: "mpc_input"
      topic_type: agimus_msgs/msg/MpcInput
      python_function_name: mpc_input_cb
pyttroller_python_params:
  robot_model_params:
    moving_joint_names:
      - fer_joint1
      - fer_joint2
      - fer_joint3
      - fer_joint4
      - fer_joint5
      - fer_joint6
      - fer_joint7
    free_flyer: false
    collision_as_capsule: false
    self_collision: false
    armature: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
  dt_factor_n_seq:
    factors: [1]
    n_steps: [5]
  ocp_params_force_feedback:
    dt: 0.002
    horizon_size: 5
    solver_iters: 20
    callbacks: false
    qp_iters: 500
    use_debug_data: false
    with_force_cost: true
    with_gravity_torque_reg: true
    frame_of_interest: fer_rightfinger
    x_reg_cost_weight: 1.0
    frame_translation_cost_weight: 1.0
    frame_rotation_cost_weight: 1.0
    frame_velocity_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    frame_velocity_cost_weight: 1.0
    Kp: [1000.0, 1000.0, 1000.0]
    Kv: [100.0, 100.0, 100.0]
    oPc_offset: [0.0, 0.0, 0.0]
    contact_type: "3D"
  trajectory_params:
    robot_configuration: [0.0, 0.580695, -0.000001, -2.594214, -0.000008, 3.17491, 1.571726]
    robot_velocity: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    w_robot_configuration: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    w_robot_velocity: [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2]
    w_robot_effort: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
    frame_of_interest: fer_rightfinger
    frame_target_pose_quat: [0.923, -0.382, 0.0, 0.0]
    frame_target_pose_position: [0.4, 0.0, 0.0]
    frame_rotation_weights: [1.0, 1.0, 1.0]
    frame_translation_weights: [3.0, 3.0, 3.0]
    desired_force: [0.0, 0.0, 0.0]
    desired_force_weights: [0.0, 0.0, 1.0]
