agimus_pytroller:
  ros__parameters:
    update_rate: 1000 # Hz
    type: agimus_pytroller/AgimusPytroller
    python_module: panda_deburring.deburring_controller
    python_downsample_factor: 2
    state_interfaces:
      - fer_joint1/position
      - fer_joint2/position
      - fer_joint3/position
      - fer_joint4/position
      - fer_joint5/position
      - fer_joint6/position
      - fer_joint7/position
      - fer_joint1/velocity
      - fer_joint2/velocity
      - fer_joint3/velocity
      - fer_joint4/velocity
      - fer_joint5/velocity
      - fer_joint6/velocity
      - fer_joint7/velocity
    command_interfaces:
      - fer_joint1/effort
      - fer_joint2/effort
      - fer_joint3/effort
      - fer_joint4/effort
      - fer_joint5/effort
      - fer_joint6/effort
      - fer_joint7/effort
    subscribed_topics: ["mpc_input"]
    mpc_input:
      topic_name: "mpc_input"
      topic_type: agimus_msgs/msg/MpcInput
      python_function_name: mpc_input_cb
