ft_calibration_filter:
  ros__parameters:
    update_rate: 1000 # has to be repeated here as in ROS 2 Humble value form the controller manager is not propagated to the controllers...
    type: panda_deburring/FTCalibrationFilter
    state_force_interfaces_names:
      - ati_mini45/force.x
      - ati_mini45/force.y
      - ati_mini45/force.z
      - ati_mini45/torque.x
      - ati_mini45/torque.y
      - ati_mini45/torque.z
    state_robot_position_interfaces_names:
      - fer_joint1/position
      - fer_joint2/position
      - fer_joint3/position
      - fer_joint4/position
      - fer_joint5/position
      - fer_joint6/position
      - fer_joint7/position
    moving_joint_names:
      - fer_joint1
      - fer_joint2
      - fer_joint3
      - fer_joint4
      - fer_joint5
      - fer_joint6
      - fer_joint7
    filtered_forces_interfaces_names:
      - agimus_pytroller/ati_mini45/force.x
      - agimus_pytroller/ati_mini45/force.y
      - agimus_pytroller/ati_mini45/force.z
      - agimus_pytroller/ati_mini45/torque.x
      - agimus_pytroller/ati_mini45/torque.y
      - agimus_pytroller/ati_mini45/torque.z
    measurement_frame_id: ati_mini45_measurement_reference
    bias_measurement_samples: 500
    gravity_vector: [0.0, 0.0, -9.81]
    invert_forces: true
    contact_detection:
      hysteresis_samples: 5
      augment_state: true
      command_interface_name: agimus_pytroller/in_contact
      lower_threshold: 0.2
      upper_threshold: 1.0
      axis_mask: "z"
    calibration:
      measurement_frame:
        xyz: [0.0, 0.0, 0.0]
        rpy: [0.088, 0.008, 0.088]
        # rpy: [0.0, 0.0, 0.0]
      com:
        xyz: [0.0, 0.0, -0.021]
        mass: 1.063
    ati_mini45/force.x:
      a: [-1.8403591709709755, 0.8521922521270615]
      b: [0.002958270289021522, 0.005916540578043044, 0.002958270289021522]
    ati_mini45/force.y:
      a: [-1.8403591709709755, 0.8521922521270615]
      b: [0.002958270289021522, 0.005916540578043044, 0.002958270289021522]
    ati_mini45/force.z:
      a: [-1.8403591709709755, 0.8521922521270615]
      b: [0.002958270289021522, 0.005916540578043044, 0.002958270289021522]
    ati_mini45/torque.x:
      a: [-1.8403591709709755, 0.8521922521270615]
      b: [0.002958270289021522, 0.005916540578043044, 0.002958270289021522]
    ati_mini45/torque.y:
      a: [-1.8403591709709755, 0.8521922521270615]
      b: [0.002958270289021522, 0.005916540578043044, 0.002958270289021522]
    ati_mini45/torque.z:
      a: [-1.8403591709709755, 0.8521922521270615]
      b: [0.002958270289021522, 0.005916540578043044, 0.002958270289021522]
agimus_pytroller:
  ros__parameters:
    type: agimus_pytroller/AgimusPytroller
    python_module: panda_deburring.deburring_controller
    python_downsample_factor: 2
    error_on_no_data: true
    interpolate_trajectory: true
    input_interfaces:
      - fer_joint1/position
      - fer_joint2/position
      - fer_joint3/position
      - fer_joint4/position
      - fer_joint5/position
      - fer_joint6/position
      - fer_joint7/position
      - fer_joint1/velocity
      - fer_joint2/velocity
      - fer_joint3/velocity
      - fer_joint4/velocity
      - fer_joint5/velocity
      - fer_joint6/velocity
      - fer_joint7/velocity
      - agimus_pytroller/ati_mini45/force.x
      - agimus_pytroller/ati_mini45/force.y
      - agimus_pytroller/ati_mini45/force.z
      - agimus_pytroller/ati_mini45/torque.x
      - agimus_pytroller/ati_mini45/torque.y
      - agimus_pytroller/ati_mini45/torque.z
      - agimus_pytroller/in_contact
    command_interfaces:
      - fer_joint1/effort
      - fer_joint2/effort
      - fer_joint3/effort
      - fer_joint4/effort
      - fer_joint5/effort
      - fer_joint6/effort
      - fer_joint7/effort
    reference_interfaces:
      - ati_mini45/force.x
      - ati_mini45/force.y
      - ati_mini45/force.z
      - ati_mini45/torque.x
      - ati_mini45/torque.y
      - ati_mini45/torque.z
      - in_contact
    subscribed_topics: ["mpc_input"]
    mpc_input:
      topic_name: "mpc_input"
      topic_type: agimus_msgs/msg/MpcInputArray
      python_function_name: mpc_input_cb
    published_topics: ["mpc_debug_data"]
    mpc_debug_data:
      topic_name: "mpc_debug"
      topic_type: agimus_msgs/msg/MpcDebug
      python_msg_getter_name: get_ocp_results
    pytroller_python_params:
      robot_model_params:
        moving_joint_names:
          - fer_joint1
          - fer_joint2
          - fer_joint3
          - fer_joint4
          - fer_joint5
          - fer_joint6
          - fer_joint7
        free_flyer: false
        collision_as_capsule: false
        self_collision: false
        armature: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
      dt_factor_n_seq:
        factors: [1]
        n_steps: [5]
      ocp_params_force_feedback:
        dt: 0.002
        horizon_size: 5
        solver_iters: 2
        callbacks: false
        qp_iters: 25
        use_debug_data: false
        with_force_cost: true
        with_gravity_torque_reg: true
        frame_of_interest: ati_mini45_measurement_reference
        x_reg_cost_weight: 1.0
        frame_translation_cost_weight: 1.0
        frame_rotation_cost_weight: 1.0
        frame_velocity_weights: [3.125, 3.125, 3.125, 2., 2., 2.]
        frame_velocity_cost_weight: 1.0
        Kp: [150.0, 150.0, 150.0]
        Kv: [0.5, 0.5, 0.5]
        oPc_offset: [0.0, 0.0, 0.0]
        contact_type: "3D"
        solver_nthreads: 16
