trajectory_publisher_node:
  ros__parameters:
    trajectory_generator_name: sanding_generator
    update_frequency: 100.0
    ocp_dt: 0.002
    n_buffer_points: 300
    measurement_frame_id: ati_mini45_measurement_reference
    tool_frame_id: fer_ati_mini45_with_camera_tool
    robot_base_frame: fer_link0
    initialization:
      max_linear_velocity: 0.1
      max_angular_velocity: 1.0
      pose_tolerance: 0.05
      rot_tolerance: 0.5
    initialize:
      robot_configuration: [0.0, 0.11352, -0.01205, -2.70992, 0.00436, 2.82343, 0.74763]
      robot_velocity: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      frame_translation: [0.5, 0.15, 0.05]
      frame_rotation: [1.0, 0.0, 0.0, 0.0]
      desired_force: [0.0, 0.0, 0.0]
      w_robot_configuration: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1]
      w_robot_velocity: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.1]
      w_robot_effort: [0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001]
      w_frame_rotation: [0.0, 0.0, 0.0]
      w_measurement_translation: [20.0, 20.0, 0.0]
      w_tool_translation: [20.0, 20.0, 10.0]
      w_frame_angular_velocity: [0.0, 0.0, 0.0]
      w_frame_linear_velocity: [0.0, 0.0, 0.0]
      w_desired_force: [0.0, 0.0, 0.0]
    seek_contact:
      robot_configuration: [0.0, 0.3977, -0.00148, -2.65091, 0.00619, 3.04861, 0.7461]
      robot_velocity: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      frame_translation: [0.5, 0.15, 0.012]
      frame_rotation: [1.0, 0.0, 0.0, 0.0]
      desired_force: [0.0, 0.0, 0.0]
      w_robot_configuration: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1]
      w_robot_velocity: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
      w_robot_effort: [0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001]
      w_frame_rotation: [0.0, 0.0, 0.0]
      w_measurement_translation: [2.0, 2.0, 0.0]
      w_tool_translation: [20.0, 20.0, 5.0]
      w_frame_angular_velocity: [0.0, 0.0, 0.0]
      w_frame_linear_velocity: [0.0, 0.0, 0.0]
      w_desired_force: [0.0, 0.0, 0.0]
    in_contact:
      robot_configuration: [0.0, 0.3977, -0.00148, -2.65091, 0.00619, 3.04861, 0.7461]
      robot_velocity: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      frame_translation: [0.5, 0.15, 0.012]
      frame_rotation: [1.0, 0.0, 0.0, 0.0]
      desired_force: [0.0, 0.0, 30.0]
      w_robot_configuration: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1]
      w_robot_velocity: [0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
      w_robot_effort: [0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001]
      w_frame_rotation: [0.0, 0.0, 0.0]
      w_measurement_translation: [20.0, 20.0, 0.0]
      w_tool_translation: [0.0, 0.0, 0.0]
      w_frame_angular_velocity: [0.0, 0.0, 0.0]
      w_frame_linear_velocity: [0.0, 0.0, 0.0]
      w_desired_force: [0.00001, 0.00001, 0.0001]
    sanding_generator:
      circle:
        radius: 0.0000000000005
        frequency: 0.5
      start_time: 0.0
