trajectory_publisher_node:
  ros__parameters:
    trajectory_generator_name: sanding_generator
    update_frequency: 100.0
    n_buffer_points: 5
    frame_of_interest: ati_mini45_measurement_reference
    initial_targets:
      robot_configuration: [0.0, 0.1865, 0.0, -2.4, 0.0, 2.5915, 0.7863]
      robot_velocity: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      frame_translation: [0.5, 0.0, 0.3]
      frame_rotation: [0.0, 0.0, 1.0, 0.0]
      desired_force: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    weights:
      robot_configuration: [0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.1]
      robot_velocity: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      robot_effort: [0.0000001, 0.0000001, 0.0000001, 0.0000001, 0.0000001, 0.0000001, 0.0000001]
      frame_rotation: [200.0, 200.0, 200.0]
      frame_translation: [120.0, 120.0, 120.0]
      frame_angular_velocity: [0.0, 0.0, 0.0]
      frame_linear_velocity: [0.0, 0.0, 0.0]
      desired_force: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    sanding_generator:
      circle:
        radius: 0.1
        frequency: 0.1
      start_time: 5.0
